### ISSUE TITLE
Does not work in HA core-2022.2.0b6

### ISSUE THREAD

**Issue by ColinRobbins** [Sennevds/media_player.template#35]
Hi,

This integration failes to load in HA core-2022.2.0b6.
This was previousl working in 2021.11.1
My log file is below.

```
Logger: homeassistant.components.media_player
Source: custom_components/media_player_template/media_player.py:298
Integration: Media Player (documentation, issues)
First occurred: 15:46:08 (1 occurrences)
Last logged: 15:46:08

Error while setting up media_player_template platform for media_player
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/homeassistant/.homeassistant/custom_components/media_player_template/media_player.py", line 157, in async_setup_platform
    async_add_entities(await _async_create_entities(hass, config))
  File "/home/homeassistant/.homeassistant/custom_components/media_player_template/media_player.py", line 205, in _async_create_entities
    MediaPlayerTemplate(
  File "/home/homeassistant/.homeassistant/custom_components/media_player_template/media_player.py", line 298, in __init__
    super().__init__(
TypeError: __init__() missing 1 required positional argument: 'hass'
```
